#!/usr/bin/env bash
# 0-change_your_home_IP - /etc/hosts faylını dəyişdirir

sudo sed -i "/^127\.0\.0\.1\s.*localhost/d" /etc/hosts
sudo sed -i "/^::1\s.*localhost/d" /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

sudo sed -i "/^.*facebook\.com/d" /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
